module.exports = [
  require("./clear"),
  require("./contacts"),
  require("./delete"),
  require("./file"),
  require("./gif"),
  require("./help"),
  require("./history"),
  require("./lock"),
  require("./logout"),
  require("./message"),
  require("./recent"),
  require("./reply"),
  require("./settings"),
  require("./threads"),
  require("./unlock"),
];
